# config/app.yml for rails-settings-cached
defaults: &defaults
  db_secret: "swgemus3cr37!"
  salt_length: 12
  theme: "Default"

development:
  <<: *defaults

test:
  <<: *defaults

production:
  <<: *defaults
